### ISSUE TITLE
Feature-Request: Select elements which should be exported

### ISSUE THREAD

**Issue by MySpace17** [CPS-IT/mask_export#105]
Feature-Request: Select elements which should be exported

With this feature it would be able to choose only specific elements which should be exported to an own extension.

**Comment by IchHabRecht** [comment]
Hi @MySpace17,

This is not possible as the export is coupled to the mask configuration. You should only provide / configure the elements within mask, you really need. In the mask repository there is a pending patch to split the mask.json into multiple files, so you can arrange your elements more flexible.
