### ISSUE TITLE
Export FontAwesome-Icon with the choosen color

### ISSUE THREAD

**Issue by TheSixtElement** [CPS-IT/mask_export#107]
It would be cool if this extension could also export the selected FontAwesome-Icon with the choosen color:
![image](https://user-images.githubusercontent.com/34134233/33437645-e3d2fede-d5e8-11e7-9301-f73c06f635db.png)

**Comment by IchHabRecht** [comment]
Hi @TheSixtElement,

Currently there is no way to pass additional parameters to the \TYPO3\CMS\Core\Imaging\IconProvider\FontawesomeIconProvider that is used for FontAwesome icons
