### ISSUE TITLE
Language: All not displayed

### ISSUE THREAD

**Issue by aschmutt** [CPS-IT/mask_export#108]
A mask_export content element with Language=All (sys_language_uid=-1) is not displayed. 
Not sure if this is a solution or a workaround: 
In Configuration/TypoScript/setup.txt add language to dataProcessing: 

    dataProcessing.10 = TYPO3\CMS\Frontend\DataProcessing\DatabaseQueryProcessor
    dataProcessing.10 {
        if.isTrue.field = tx_mask_content_1
        table = tt_content
        pidInList.field = pid
        where = tx_mask_content_1_parent=###uid### AND deleted=0 AND hidden=0 AND colPos='999'  AND sys_language_uid IN (###language###, -1)
        orderBy = sorting
        markers {
            uid.field = uid
            language.field = sys_language_uid
        }
        languageField = 0
        as = data_tx_mask_content_1
    }

This was tested in a environment with only one language (sys_languag_uid=0). 
Issue is in both 7.6 and 8.7

**Comment by IchHabRecht** [comment]
Hi @aschmutt,

As the export doesn't care about the sys_language_uid at all (there is no constraint added at all), I don't understand the problem completely. Would you mind to share more information about your setup? Have you changed anything manually? Which version of mask_export are you using?

Thanks for your help.

**Comment by aschmutt** [comment]
I just tested again, and realized this seems to be default TYPO3 behaviour. Not sure if its a bug or a wanted behavior?  

- Single-Language setup, no specific language settings, so everything is default
- sys_language_uid=0 is displayed (Language=Default)
- sys_language_uid=-1 not displayed (Language=All)
- I tried some config language parameters, this did not change anything

Test1: TYPO3 8.7.6, mask_export 0.9.1
Test2: TYPO3 7.6.23, mask_export 0.9.1

**Comment by IchHabRecht** [comment]
Hi @aschmutt,

Sorry I came back that late, but I still do not understand the problem. The language handling of the DatabaseQueryProcessor is done in typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:7479 and includes sys_language_uid -1 as well. As this is all done with proper TYPO3 Api I have no clue how I can help you with the mask_export extension. If possible, please give me some more information about your installation or create a forge issue ticket for the TYPO3 core itself (see https://forge.typo3.org/projects/typo3cms-core/issues).

**Comment by aschmutt** [comment]
yes this can be closed here - this is not related to mask_export, its from TYPO3 core. I just noticed it here first, as I use it in most of my projects.
