### ISSUE TITLE
Fehler "Wert ist nicht erlaubt"

### ISSUE THREAD

**Issue by blueamerican** [CPS-IT/mask_export#109]
TYPO3 8
mask 3.0.1
mask_export 0.9.1

Nach dem Exportieren installiere ich die Extension.

Ich möchte ein neues Element erstellen und bekomme den Fehler wie oben.
Analog #106 

Ich habe herausgefunden woran das liegt:

in TCA\Overrides\tt_content.php
wurde dieser code hier generiert:

```
<?php
$GLOBALS['TCA']['tt_content']['columns']['CType']['config']['items'][] = array(
    'LLL:EXT:teste/Resources/Private/Language/locallang_db.xlf:tt_content.CType.div._teste_',
    '--div--',
);
$tempTypes = array (
);
$GLOBALS['TCA']['tt_content']['types'] += $tempTypes;
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile(
    'teste',
    'Configuration/TypoScript/',
    'teste'
);
```
Der ist jedoch nicht vollständig.

Wenn ich mir den vollständigen Code aus dem Backend (Reiter Code Export) hole, funktioniert es.

Warum wird der Code nicht richtig generiert?

**Comment by IchHabRecht** [comment]
Hi @blueamerican,

After you created your content elements with mask, have you cleared the cache to force all elements to be available?

**Comment by blueamerican** [comment]
i already realized it. clearing cache solves this issue. thanks.
