### ISSUE TITLE
Avoid self destruction when no extension key is provided

### ISSUE THREAD

**Issue by smichaelsen** [CPS-IT/mask_export#110]
mask_export should not use its own extension key as default export extension key, because it will overwrite itself with the exported code when using the Write feature.

My suggestion is to leave the export extension key blank by default and make it a mandatory field so the user has to provide an extension key explicitly.

**Comment by IchHabRecht** [comment]
As I don't want the user to have to deal with an extension key on its first export, I decided to change that one to "my_mask_export".
