### ISSUE TITLE
[BUG] Colpos will be 0 instead of 999 when using containers as Non-Admin user

### ISSUE THREAD

**Issue by manuelbachl** [CPS-IT/mask_export#71]
Hi Nicole,

I'm not 100% sure, wether this is a mask_export related bug, but may be.

When I'm building content elements which act as a container, nested contents will get colpos 999 as mask default. This totally works fine when creating contents as an administrator. But when creating new contents as a non-admin user, the colpos which is stored in the database will be 0, which breaks the whole template. Unfortunately I can't tell which changes I have done befor getting this issue :-(
If you need more info, let me know.

Regards, Manuel

**Comment by manuelbachl** [comment]
My composer.json for possible simulation:

```
{
  "name": "...",
  "license": "MIT",
  "type": "project",
  "description": "...",
  "authors": [
    {
      "name": "Manuel Bachl",
      "email": "..."
    }
  ],
  "repositories": [
    {
      "type": "composer",
      "url": "https://composer.typo3.org/"
    },
    {
      "type": "vcs",
      "url": "https://github.com/Gernott/mask.git"
    },
    {
      "type": "vcs",
      "url": "https://github.com/IchHabRecht/TYPO3-mask_export.git"
    }
  ],
  "require": {
    "php": "^7.0.0",
    "typo3/cms": "8.6.1 as 8.2.0",
    "typo3/cms-indexed-search": "^8.6",
    "helhum/typo3-console": "4.2.*",
    "spooner-web/just_news": "^0",
    "dmitryd/typo3-realurl": "2.1.5",
    "typo3-ter/devlog": "3.0.1",
    "t3monitor/t3monitoring_client": "^1"
  },
  "autoload": {
    "psr-4": {
      "UEBB\\WebsiteTemplate\\": "web/typo3conf/ext/website_template/Classes",
      "UEBB\\DistributorSearch\\": "web/typo3conf/ext/distributor_search/Classes"
    }
  },
  "require-dev": {
    "mask/mask": "dev-master as 2.1.2",
    "cpsit/mask-export": "dev-master as 0.7.0"
  },
  "autoload-dev": {

  },
  "scripts": {

  },
  "extra": {
    "typo3/cms": {
      "cms-package-dir": "{$vendor-dir}/typo3/cms",
      "web-dir": "web"
    },
    "helhum/typo3-console": {
      "install-extension-dummy": false
    }
  }
}
```

**Comment by IchHabRecht** [comment]
Hi Manuel,

Thank you for your report. I don't need any composer.json. Instead I would need either the mask.json or your export extension. In the mean time I tried to reproduce the problem you reported but couldn't. The element from an editor was stored and restored properly. Is the correct column visible for your editor on adding new inline elements to the container?

**Comment by manuelbachl** [comment]
Hi Nicole, well, now i have the .zip and the mask.json ready.

[website_template.zip](https://github.com/CPS-IT/TYPO3-mask_export/files/892863/website_template.zip)
[mask.json.zip](https://github.com/CPS-IT/TYPO3-mask_export/files/892865/mask.json.zip)

thx for your help

**Comment by manuelbachl** [comment]
Hi Nicole, this one seems to be fixed with update to 8.7 - but let me verify this when deploying the site. I think somewhen in the next week i know more

**Comment by IchHabRecht** [comment]
I found an error within the export and TYPO3 8.7. Maybe this is related to your problem? I have changed the exported PHP code for the dataProvider. Maybe you want to have a look at this one.

**Comment by IchHabRecht** [comment]
Can this issue be closed or does the problem still exists?

**Comment by manuelbachl** [comment]
Can be closed IMO. I'm using 0.9.1 and there everything is fine

**Comment by manuelbachl** [comment]
Well, no problems anymore - was our fault

**Comment by IchHabRecht** [comment]
Hi Manuel,

Thanks for your feedback!
