### ISSUE TITLE
ExtensionManagementUtility::addStaticFile in TCA/Overrides/tt_content.php

### ISSUE THREAD

**Issue by smichaelsen** [CPS-IT/mask_export#83]
mask_export writes something like this to `Configuration/TCA/Overrides/tt_content.php`:

````php
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile(
    'myext',
    'Configuration/TypoScript/',
    'myext'
);
````

IMO this belongs into `Configuration/TCA/Overrides/sys_template.php`, because that's the table which is changed by `ExtensionManagementUtility::addStaticFile()`.

**Comment by IchHabRecht** [comment]
The name of the file doesn't matter for TYPO3. To prevent further new files for single lines, I wrote this one into the tt_content one.
