### ISSUE TITLE
Error: Class 'MASKCONT\Maskcont\Form\FormDataProvider\TcaColPosItem' not found

### ISSUE THREAD

**Issue by blueamerican** [CPS-IT/mask_export#86]
TYPO3 8.7.1 or 8.7.4
Mask Export 0.9.1

**Question 1:**
When exporting a mask content element with a CONTENT Element, there is a class added:

typo3conf\ext\maskcont\Classes\Form\FormDataProvider\TcaColPosItem.php

in ext_localconf.php the following lines are added:

```
$GLOBALS['TYPO3_CONF_VARS']['SYS']['formEngine']['formDataGroup']['tcaDatabaseRecord'][\MASKCONT\Maskcont\Form\FormDataProvider\TcaColPosItem::class] = [
    'depends' => [
        \TYPO3\CMS\Backend\Form\FormDataProvider\DatabaseRowDefaultValues::class,
    ],
    'before' => [
        \TYPO3\CMS\Backend\Form\FormDataProvider\TcaSelectItems::class,
    ],
];
```

For me this doesn't work.
I get the error see screen below.

**Question 2:**
Why is this class only added when i use a CONTENT Element? In former version of mask_export, this class, which is necessary for the backend preview i guess, was also added when using a REPEATED Element.
btw: Where is the hook gone?
![mask_export](https://user-images.githubusercontent.com/5647051/28688882-c92d07ce-7313-11e7-941c-002abd35b123.jpg)

**Comment by IchHabRecht** [comment]
Hi Markus,

Question 1:

Are you using composer to set up your TYPO3 installation? Have you configured a psr-4 autoload information for your export extension then?

Question 2:

The mentioned class is only needed for nested content elements, to be able to move the IRRE elements to their own colPos. Maybe you mix it up with the page layout hook for the backend preview? This is only generated if you switched on the settings in mask_export configuration (in Extension Manager).

Does this solve your problems?

**Comment by blueamerican** [comment]
yes Question 1 is a composer issue.
Question 2:
Yes i mixed it up. I take a look at the EM, i searched for this configuration:-)
Thanks a lot.
