### ISSUE TITLE
ERROR when choosing the new content Element: WERT IST NICHT ERLAUBT

### ISSUE THREAD

**Issue by blueamerican** [CPS-IT/mask_export#87]
TYPO3 8.7.1. 8.7.4
mask_export 0.9.1

when selecting a CE created with mask_export, i get the error below
![mask_export1](https://user-images.githubusercontent.com/5647051/28689092-ab2397ba-7314-11e7-9be3-076e4fcad579.jpg)

**Comment by IchHabRecht** [comment]
Hi Markus,

I fear this isn't any mask_export related problem. Somewhere your CType items are manipulated. Maybe you are using any itemsproc function for your CTypes? Are you using any extension like gridelements and/or content_defender that may restrict the available CTypes for a colPos? Are you using any editor with limited restrictions? Maybe pageTS is configured to a whitelist of elements only?

Can you give some more input about your installation? For example the configuration for tt_content->CType and/or installed extensions?

**Comment by blueamerican** [comment]
i tried it on another Server and there it worked. Other Extensions must have been the reason, thanks!
