### ISSUE TITLE
error #1476107295: PHP Warning: htmlspecialchars() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by blueamerican** [CPS-IT/mask_export#89]
error with preview checkbox clicked in Extension manager.

When opening a page with a CE from mask_export (contains only one image element), i get the following error:
#1476107295: PHP Warning: htmlspecialchars() expects parameter 1 to be string, array given

see also screen
TYPO3 8.7.4
mask_export 0.9.1
![mask](https://user-images.githubusercontent.com/5647051/29558383-2e3e994e-872c-11e7-828f-32e8300c1741.jpg)

**Comment by blueamerican** [comment]
the reason is the code in the generated backend template

**Comment by IchHabRecht** [comment]
Hi Markus,

Thank you for your report. I found the problem within the TYPO3 CMS and fixed the template generation. Would you mind to test the pull request #92 

Thank you very much.
