### ISSUE TITLE
Put labels of select items into locallang file

### ISSUE THREAD

**Issue by smichaelsen** [CPS-IT/mask_export#99]
While all field labels are correctly written to `locallang_db.xlf` the labels of select items are hardcoded into `TCA/Overrides/tt_content.php`. For consistency and being better translatable they should be included in the locallang file as well.

**Comment by smichaelsen** [comment]
I'm not sure, maybe this is something that has to be fixed in `mask`.

**Comment by IchHabRecht** [comment]
Hi Sebastian,

As mask doesn't support any labels, I guess I have to care about it in mask_export. I need to have a look which fields I have to take care of and write some new lines of code to parse the items.

Will think about that :-)
